version: '3'

tasks:

  server:
    aliases: [s]
    cmds:
     - docker run -p 50051:50051 --rm -it cpp-grpc-server

  build_server:
    aliases: [bs]
    cmds:
     - docker build -t cpp-grpc-server -f .\server\Dockerfile .

  client:
    aliases: [c]
    cmds:
     - cd client && task main

  build_client:
    aliases: [bc]
    cmds:
     - cd client && task build