version: '3'

tasks:
  server:
    desc: "Run the Spring Boot OSLC Server"
    dir: server
    aliases: [s]
    cmds:
      - mvn spring-boot:run

  client:
    desc: "Run the SvelteKit OSLC Client"
    aliases: [c]
    dir: client
    cmds:
      - bun run dev

  test-client:
    desc: "Run Vitest integration tests for SvelteKit OSLC Client"
    aliases: [tc]
    dir: client
    cmds:
      - bunx vitest run

  kill:
    desc: "Kill all running processes"
    aliases: [k]
    cmds:
      - taskkill /F /IM java.exe
      - taskkill /F /IM bun.exe
      - taskkill /F /IM node.exe

  dev:
    desc: "Run both the Svelte client and Spring Boot server concurrently"
    deps: [server, client]
