version: "3"

tasks:
  default:
    deps: [main_post]

  main:
    aliases: [m]
    cmds:
      - uv run main.py

  main_post:
    aliases: [p]
    cmds:
      - uv run main_post.py

  zip:
    aliases: [z]
    cmds:
      - uv run _zip.py
