version: "3"

tasks:
  default:
    deps: [build]

  build:
    cmds:
      - emcc sum.c -o wasm_sum.js 
        -s WASM=1 -s EXPORTED_FUNCTIONS='["_sum"]' 
        -s EXPORTED_RUNTIME_METHODS='["ccall", "cwrap"]' 
        -s MODULARIZE=1 -s EXPORT_NAME='WasmSum'
  
  run: 
    cmds:
      - bun run main.ts