version: '3'

tasks:
  default:
    desc: "List available tasks"
    cmds:
      - task --list

  run:
    aliases: [r]
    desc: "Run the module example"
    cmds:
      - cargo run

  test:
    aliases: [t]
    desc: "Test the module example"
    cmds:
      - cargo test

  clear:
    desc: "Delete Cargo build artifacts"
    cmds:
      - cargo clean
