version: '3'

tasks:

  default:
    deps: [cmake]


  cmake:
    cmds:
      - cmake -G "Ninja" -DCMAKE_TOOLCHAIN_FILE=../wasm.toolchain.cmake -B build
      - cmake --build build

  build:
    aliases: [b]
    cmds:
      - clang --target=wasm32 --no-standard-libraries -Wl,--export-all -Wl,--no-entry -o add.wasm src/add.c


  run:
    deps: [cmake]
    aliases: [r]
    cmds:
      - bun run run.ts


  main:
    deps: [build]
    aliases: [m]
    cmds:
     - bun run run.ts

  clear:
    aliases: [c]
    cmds:
     - powershell rm add.wasm
