version: "3"

tasks:
  default:
    cmds:
      - task --list

  hi:
    desc: "Run a test prompt"
    cmds:
      - uv run -m app.main -p "hi"

  run:
    aliases: ["r"]
    desc: "Run the Application"
    cmds:
      - uv run -m app.main -p {{.CLI_ARGS}}

  test:
    desc: "Test the Step"
    vars:
      PROMPT: "what is the content of Taskfile.yml?"
    cmds:
      - uv run -m app.main -p "{{.PROMPT}}"
