"$schema" = 'https://starship.rs/config-schema.json'

format = """
$hostname\
$directory\
$git_branch\
$git_state\
$git_status\
$username\
$python\
$java\
$nodejs\
$cmd_duration\
$battery\
$line_break\
$character"""

[username]
disabled = false
show_always = true
format = "[\uf007 $user]($style) "

[directory]
style = "fg:#3de1f3"
# format = "[ \u0001f4c1  $path ]($style)"
# format = "[🖿 $path ]($style)"
format = "[$path ]($style)"

[battery]
full_symbol = '🔋 '
charging_symbol = '⚡ '
discharging_symbol = '🪫 '
format = "[\\($symbol$percentage\\)]($style)"

[[battery.display]]
threshold = 15
style = 'bold red'

[[battery.display]]
threshold = 40
style = 'bold yellow'

# [[battery.display]]
# threshold = 100
# style = 'green'

[character]
success_symbol = "[\ue007](fg:#3de1f3)"
# success_symbol = "[\uf072 ](fg:#3de1f3)"
# success_symbol = "[\uf1d8 ](fg:#3de1f3)"
# success_symbol = "[\uf1d9 ](fg:#3de1f3)"

error_symbol = "[❯](red)"
vimcmd_symbol = "[❮](green)"

[git_branch]
format = "[$symbol$branch ]($style fg:#a3be8c)"

[git_status]
style = "bold fg:#a3be8c"
format = "([\\[$all_status$ahead_behind\\]]($style) )"
ahead = "⇡"
behind = "⇣"
diverged = "⇕"
untracked = "?"
modified = "!"
staged = "+"
renamed = "»"
deleted = "✘"
stashed = ""

[git_state]
style = "bold fg:#a3be8c"
format = '\([$state( $progress_current/$progress_total)]($style)\) '

[cmd_duration]
format = "[ $duration]($style) "
style = "bold fg:#f3d97b"

[python]
format = "[\\[py $version( )\\]]($style)([ \\($virtualenv\\)]($style))"
style = "fg:#758199"

[java]
format = "[\\[java $version\\]]($style) "
style = "fg:#758199"

[nodejs]
format = "[\\[node $version\\]]($style) "
style = "fg:#758199"
