"$schema" = 'https://starship.rs/config-schema.json'

format = """
$hostname\
$directory\
$git_branch\
$git_state\
$git_status\
$username\
$python\
$java\
$nodejs\
$cmd_duration\
$battery\
$line_break\
$character"""

[username]
disabled = false
show_always = true
format = "[\uf007 $user]($style) "

[directory]
style = "fg:#3de1f3"
# format = "[ \u0001f4c1  $path ]($style)"
# format = "[🖿 $path ]($style)"
format = "[$path ]($style)"

[battery]
full_symbol = '🔋 '
charging_symbol = '⚡ '
discharging_symbol = '🪫 '
format = "[\\($symbol$percentage\\)]($style)"

[[battery.display]]
threshold = 15
style = 'bold red'

[[battery.display]]
threshold = 40
style = 'bold yellow'

# [[battery.display]]
# threshold = 100
# style = 'green'

[character]
success_symbol = "[ ](fg:#3de1f3)" # U+E007

error_symbol = "[❯](red)"
vimcmd_symbol = "[❮](green)"

[git_branch]
format = "[$symbol$branch ]($style fg:#a3be8c)"

[git_status]
style = "bold fg:#a3be8c"
format = "([\\[$all_status$ahead_behind\\]]($style) )"
ahead = "⇡"
behind = "⇣"
diverged = "⇕"
untracked = "?"
modified = "!"
staged = "+"
renamed = "»"
deleted = "✘"
stashed = ""

[git_state]
style = "bold fg:#a3be8c"
format = '\([$state( $progress_current/$progress_total)]($style)\) '

[cmd_duration]
format = "[ $duration]($style) "
style = "bold fg:#f3d97b"

[python]
format = "[\\[py $version( )\\]]($style)([ \\($virtualenv\\)]($style))"
style = "fg:#758199"

[java]
format = "[\\[java $version\\]]($style) "
style = "fg:#758199"

[nodejs]
format = "[\\[node $version\\]]($style) "
style = "fg:#758199"

# Useful Symbols
#  U+E007    U+E209    U+E220    U+E228    U+E22D  
#  U+E22E    U+E231    U+E234    U+E238    U+E23F  
#  U+E243    U+E245    U+E262    U+E2A2    U+E2A6  
#  U+E351    U+E36A    U+E36E    U+E3BF    U+E5FE  
#  U+E5FF    U+E62E    U+E70F    U+E712    U+E7BA  
#  U+EA81    U+EB44    U+F060    U+F061    U+F062  
#  U+F063    U+F064    U+F065    U+F066    U+F072  
#  U+F07B    U+F07C    U+F080    U+F1D8    U+F1D9  
#  U+F1E2    U+F240    U+F241    U+F242    U+F243  
#  U+F244    U+F36F    U+F489    U+F526
