version: "3"

vars:
  CC: uvx --from ziglang@0.16.0 zig cc
  CFLAGS: >-
    -O3 -std=gnu17 -Wall -Wextra -pedantic -Wno-strict-prototypes
  WIDTH: 120
  HEIGHT: 24
  TIMESTEP: 0.01
  RESTITUTION: 0.5
  FRICTION: 0.5
  RPM: 750
  FASTRPM: 4000
  TILT: 5
  EXT: '{{if eq OS "windows"}}.exe{{end}}'
  DEFINES: >-
    -DW={{.WIDTH}} -DH={{.HEIGHT}} -Ddt={{.TIMESTEP}}
    -De={{.RESTITUTION}} -Du={{.FRICTION}} -Drpm={{.RPM}}
    -Dtilt={{.TILT}}
  DEFINES_FAST: >-
    -DW={{.WIDTH}} -DH={{.HEIGHT}} -Ddt={{.TIMESTEP}}
    -De={{.RESTITUTION}} -Du={{.FRICTION}} -Drpm={{.FASTRPM}}
    -Dtilt={{.TILT}}
  APP: "build/tipple.exe"

silent: true

tasks:
  default:
    desc: List available tasks
    cmds:
      - task --list

  build:
    aliases: [b]
    desc: Build prog and tipple with zig cc
    cmds:
      - mkdir -p build
      - "{{.CC}} {{.CFLAGS}} {{.DEFINES_FAST}} prog.c -o {{.APP}}"

  run:
    aliases: [r]
    desc: Run the fast tipple-top simulation (tippe-top2.txt)
    vars:
      EXE: "build/tipple.exe"
      MODEL: "./model/tippe-top2.txt"
    deps:
      - build
    cmds:
      - powershell "Get-Content {{.MODEL}} | {{.APP}}"

  clean:
    aliases: [c]
    desc: Remove build artifacts
    cmds:
      - powershell "Remove-Item -Force -R build -ErrorAction SilentlyContinue"
    ignore_error: true
