version: '3'

tasks:

  default:
    deps: ["main"]

  main:
    aliases: ["m"]
    cmds:
      - uv run server.py

  proto:
    aliases: ["p"]
    cmds:
      - uv run -m grpc_tools.protoc -I.. --python_out=. --grpc_python_out=. service.proto

  clear:
    aliases: ["c"]
    cmds:
      - 