version: '3'

tasks:
  default:
    deps: 
      - copy

  build:
    cmds:
    - go build

  copy:
    deps: 
      - build
    cmds:
      - cp tgen.exe C:/SANDBOX/APP/bin

  test:
    aliases:
      - t
    cmds:
      - go test ./testing