version: '3'

tasks:
  main:
    desc: Run the Go backend / CLI
    cmds:
      - go run main.go
    
  web:dev:
    desc: Run the Electron Svelte Web App in development mode
    dir: web
    cmds:
      - npm run dev

  web:build:
    desc: Build the Electron Svelte Web App
    dir: web
    cmds:
      - npm run build

  web:install:
    desc: Install dependencies for the Web App
    dir: web
    cmds:
      - npm install

  web:agentation:
    desc: "Run the agentation server"
    cmds:
      - npx agentation-mcp server

  web:dist:
    desc: "Generate Windows executable (.exe)"
    dir: web
    cmds:
      - npm run build:win