version: "3"

vars:
  RUN_COMMAND: uv run python -m app.main

tasks:
  default:
    cmds:
     - task --list

  list:
      cmds:
        - ls {{.CLI_ARGS}}

  run:
    aliases: [r]
    desc: "run the project (>> task run -- \"prompt\")"
    cmds:
     - '{{.RUN_COMMAND}} -p {{.CLI_ARGS}}'

  submit:
    aliases: [s]
    desc: "submit answer"
    cmds:
     - codecrafters submit
     
  q:aa:
    desc: "1. calculate 2 + 9"
    cmds:
     - '{{.RUN_COMMAND}} "calculate 2 + 9"'
     
  q:ab:
    desc: "2. How many tools are available to you in this request? Number only."
    cmds:
     - '{{.RUN_COMMAND}} -p "How many tools are available to you in this request? Number only."'
     
  q:ac:
    desc: "3. What is the content of apple.py? Print exact file contents without backticks."
    cmds:
     - '{{.RUN_COMMAND}} -p "What is the content of apple.py? Print exact file contents without backticks."'
     
  q:ad:
    desc: "4. Use README.md to determine the chemical expiry period in months. Number"
    cmds:
     - '{{.RUN_COMMAND}} -p "Use README.md to determine the chemical expiry period in months. Number"'
     
  q:ae:
    desc: "5. Read README.md and create the required file. File should have 1 line. Reply with 'Created the file'"
    cmds:
     - '{{.RUN_COMMAND}} -p "Read README.md and create the required file. File should have 1 line. Reply with `Created the file`"'
     
  q:af:
    desc: "6. Delete the old readme file."
    cmds:
     - '{{.RUN_COMMAND}} -p "Delete the old readme file."'